### ISSUE TITLE
players.get_players() appears to be missing the rookie class of 2022

### ISSUE THREAD

**Issue by lebrennie** [swar/nba_api#368]
Maybe I'm missing something because I'm not much of a programmer, but calling the following code doesn't include the class of 2022:

from nba_api.stats.static import players
player_dict = players.get_players()
print(player_dict)

**Comment by lebrennie** [comment]
For example, if I do this: 

`from nba_api.stats.static import players
import pandas as pd

player_dict = players.get_players()
print(player_dict)`

It of course outputs the whole player dictionary, but there's no Mathurin, no Eason, no Keegan Murray, no Jalen Duren, etc. 

Also, I get an import error (ImportError: cannot import name 'playerindex' from 'nba_api.stats.endpoints' (C:\Users\Brennie\anaconda3\lib\site-packages\nba_api\stats\endpoints\__init__.py) every time I try to import the playerindex endpoint. The other endpoints all seem to be fine.

I don't think I have an older version of nba_api or anything like that. I just did 'pip install nba_api' a few days ago so I should be up to date. 

Apologies if I'm taking up time with a mistake that's on my end, but it doesn't seem to be working as far as I can tell.

**Comment by lebrennie** [comment]
My mistake, this is all working fine in v1.2.1
