### ISSUE TITLE
[Bug]: cannot import name 'team_index_championship_year' from 'nba_api.stats.library.data'

### ISSUE THREAD

**Issue by winchcodes** [swar/nba_api#284]
### NBA API Version

V1.1.12

### Issue

Working on Linux Ubuntu 22.04 LTS
Installed nba_api using  (!pip install) in a jupyter notebook cell. 
Getting an ImportError when I try to import (teams) using 'from nba_api.stats.static import teams'

### Code

``` In [ 66 ] : !pip install nba_api ```
``` In [ 67 ] : from nba_api.stats.static import teams ```

**Comment by llimllib** [comment]
looks like it was removed in 49afe0166711fc6ad706513bf86c19d40039be0b:

```
$ git show 49afe0166711fc6ad706513bf86c19d40039be0b | grep champion
-team_index_championship_year = 7
```
