### PR TITLE
Fix team_index_championship_year

### LINKED ISSUE #284: [Bug]: cannot import name 'team_index_championship_year' from 'nba_api.stats.library.data'
### NBA API Version

V1.1.12

### Issue

Working on Linux Ubuntu 22.04 LTS
Installed nba_api using  (!pip install) in a jupyter notebook cell. 
Getting an ImportError when I try to import (teams) using 'from nba_api.stats.static import teams'

### Code

``` In [ 66 ] : !pip install nba_api ```
``` In [ 67 ] : from nba_api.stats.static import teams ```

### PR DESCRIPTION
**Pull request by llimllib**
- add championship years to data-updater template
- re-add team_index_championship_year to static data
- add Bucks 2021 championship and GSW 2022

Testing:

- I replaced the broken `data.py` in my local copy of the library with the one in this PR, and then `from nba_api.stats.static import teams` worked instead of throwing an exception
- I added the world's single simplest test, on the theory that any test that imported this file would have thrown an error and so this test would catch it in the future

closes #284

cc @rsforbes

### CODE REVIEW

**Review by rsforbes — APPROVED** [review]
@llimllib - Many Thanks!
